export type { AdmissionService } from "./admissions";
export { acceptSeat, confirmExternalAdmission, getAdmissionEvents, getCandidateCurrentAdmission, getProgrammeVacancies, isAdmissionSimulationStateValid, offerSeat, releaseSeat, resetAdmissionSimulation, returnOfferedSeat, sanitizeAdmissionSimulationState, withdrawCurrentAdmission } from "./admission-state";
export type { CandidateService } from "./candidates";
export type { CollegeService } from "./colleges";
export type { OfficialCatalog, OfficialCatalogService } from "./official-catalog";
export { getPreferenceConsequence, normalizePreferencePositions, reorderPreferences, reviewPreferenceList } from "./preference-safety";
export { mockCandidateService, mockCollegeService, mockOfficialCatalogService, mockSpotRoundService } from "./mock";
export type { SeatService } from "./seats";
export type { SpotRoundService } from "./spot-rounds";
export { acceptSpotRoundOffer, advanceSpotRound, declineSpotRoundOffer, expireSpotRoundOffer, getActiveSpotInterestCount, getCandidateSpotStatus, getSpotRoundAvailableSeats, isActiveSpotInterest, joinSpotRound, leaveSpotRound } from "./spot-round-state";
export { acceptClearingOffer, advanceHeroClearingScenario, buildMeritList, declineClearingOffer, generateClearingOffers, getActiveClearingInterestCount, getCandidateClearingInterest, getCandidateMeritPosition, getClearingCandidate, getRoundAwaitingOffers, isActiveClearingInterest, isMeritClearingStateValid, joinClearingRound, leaveClearingRound } from "./clearing-network";
export { cloneDocumentPassportState, connectDocumentProvider, getAccessibleDocumentTypes, getDocumentActivity, getDocumentRecord, getLatestDocumentShare, getWorkflowReadiness, isDocumentPassportStateValid, revokeDocumentConsent, shareDocumentsForPurpose } from "./document-passport";
export { buildScholarshipEvaluationContext, cloneScholarshipNavigatorState, evaluateAllSchemes, evaluateScheme, getScholarshipSummary, isScholarshipNavigatorStateValid, recordScholarshipPortalHandoff, updateScholarshipProfile } from "./scholarships";
export type { ScholarshipEvaluationContext, ScholarshipProfileUpdate } from "./scholarships";
export type { ShareDocumentsInput } from "./document-passport";
export { buildAssistantContextSnapshot } from "./assistant-context";
export { ADMISSION_ASSISTANT_INSTRUCTIONS, DeterministicDemoAssistantProvider, getAssistantProvider, MockAssistantProvider, OpenAIResponsesAssistantProvider } from "./assistant-provider";
export type { AssistantProvider } from "./assistant-provider";
export { ASSISTANT_READ_ONLY_TOOL_NAMES, runAssistantTool, runToolsForMessage, selectAssistantTools } from "./assistant-tools";
export type { AssistantReadOnlyToolName, AssistantToolResult } from "./assistant-tools";
export { ASSISTANT_LIMITS, isAssistantContextSnapshot, validateAssistantRequest } from "./assistant-validation";
