export type { AdmissionService } from "./admissions";
export { acceptSeat, confirmExternalAdmission, getAdmissionEvents, getCandidateCurrentAdmission, getProgrammeVacancies, isAdmissionSimulationStateValid, offerSeat, releaseSeat, resetAdmissionSimulation, returnOfferedSeat, sanitizeAdmissionSimulationState, withdrawCurrentAdmission } from "./admission-state";
export type { CandidateService } from "./candidates";
export type { CollegeService } from "./colleges";
export type { OfficialCatalog, OfficialCatalogService } from "./official-catalog";
export { getPreferenceConsequence, normalizePreferencePositions, reorderPreferences, reviewPreferenceList } from "./preference-safety";
export { mockCandidateService, mockCollegeService, mockOfficialCatalogService, mockSpotRoundService } from "./mock";
export type { SeatService } from "./seats";
export type { SpotRoundService } from "./spot-rounds";
export { acceptSpotRoundOffer, advanceSpotRound, declineSpotRoundOffer, expireSpotRoundOffer, getActiveSpotInterestCount, getCandidateSpotStatus, getSpotRoundAvailableSeats, isActiveSpotInterest, joinSpotRound, leaveSpotRound } from "./spot-round-state";
export { acceptClearingOffer, advanceHeroClearingScenario, buildMeritList, declineClearingOffer, generateClearingOffers, getActiveClearingInterestCount, getCandidateClearingInterest, getCandidateMeritPosition, getClearingCandidate, getRoundAwaitingOffers, isActiveClearingInterest, isMeritClearingStateValid, joinClearingRound, leaveClearingRound } from "./clearing-network";
